name: SushiSwap
description: Allow the trading of tokens on Scroll network.
title: Add Scroll to SushiSwap
labels: ["integration"]
body:
  - type: input
    id: integration_name
    attributes:
      label: SushiSwap
      placeholder: DEX
    validations:
      required: true
  - type: dropdown
    id: integration_type
    attributes:
      label: "Project type"
      options:
        - Library
        - Tool
    validations:
      required: true
  - type: input
    id: integration_site_link
    attributes:
      label: "Site of the project"
      placeholder: https://www.sushi.com/
    validations:
      required: true
  - type: input
    id: integration_github_link
    attributes:
      label: "Github repository of the project"
      placeholder: https://github.com/sushiswap
    validations:
      required: true
  - type: dropdown
    id: integration_network
    attributes:
      label: "Networks"
      description: "On which networks should this be supported? (You can pick multiple options)"
      multiple: true
      options:
        - Scroll Mainnet
    validations:
      required: true
  - type: textarea
    id: integration_description
    attributes:
      label: "Additional context"
      description: "Describe any context, screenshot or specification of changes here"
    validations:
      required: false
